### ISSUE TITLE
1.771 - issue with let's Encrypt renewal

### ISSUE THREAD

**Issue by Skouat** [VultureProject/vulture3-gui#17]
Hi,

After creating an LE certificate and applying it to an application, the certificate is recognized.
But after a renewal, the application indicates that the certificate has expired.

In Vulture PKI manager, ther cert indicates the correct date.
But even if I reload all application listeners or stop/start all, the old certificate continues to be provided by Vulture.

To workaround this issue, I do the following steps:
  - Go to Applications to edit "my_applicatition".
  - On tabs Network, I select another certificate profile (or none).
  - I save the changes and reload application listeners.
  - Then, I go back to application network settings to define the certs previously used.
  - To finish, I reload all applications listeners.

the new certs is now properly setup.

**Comment by KGuillemot** [comment]
Hello @Skouat 
Could you please confirm us that you issue is solved with the new release 1.79.
Thank you by advance.
KGuillemot

**Comment by Skouat** [comment]
Hi @KGuillemot 

Thanks for the fix.
I will check this at the next renewal, which will be on mid-october.

**Comment by Skouat** [comment]
Hi @KGuillemot 
When the LE certificat should be renewed?
My cert will expire next week
![image](https://user-images.githubusercontent.com/25386247/137284136-1e5092c0-75e8-409a-a098-2a764abcc8ff.png)

**Comment by Skouat** [comment]
The issue is still there.
I had to edit the application and click save then reload the interface to apply the new certificate.
Also, and maybe this is just for my Vulture server, the "acme-renew.py" script doesn't seem to be executed via cron tasks. I have to run it manually.

**Comment by Skouat** [comment]
Ref : #24
